app.version=0.0.1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method
springdoc.packagesToScan=org.example.person.controllers

spring.security.username=admin
spring.security.password=admin123
